source 'https://github.com/mustachedk/MustachePodSpec.git'
source 'https://github.com/cocoapods/specs.git'

platform :ios, '11.0'

use_frameworks!

target 'MustacheRxSwift_Example' do
  pod 'MustacheRxSwift', :path => '../'

  target 'MustacheRxSwift_Tests' do
    inherit! :search_paths


  end
end
